# This is a basic workflow to help you get started with Actions

name: hola-mundo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  process-js:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Validate JavaScript
      run: node --check hola-mundo.js
      
    - name: Run JavaScript file
      run: node hola-mundo.js > output.txt
      
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: js-output
        path: output.txt

   
